stages:
  - build
  - test
  - deploy

build:
  image: node:latest
  stage: build
  before_script:
    - npm install
  script:
    - npm run build
    - echo "Build completed on $(date)"
  artifacts:
    paths:
      - ./build

unit-test:
  image: node:latest
  stage: test
  before_script:
    - npm install
  script:
    - npm run test:ci
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    paths:
      - coverage/
    when: always
    reports:
      junit:
        - junit.xml

deploy:
  image: docker:edge-git  
  stage: deploy
  before_script:
    - apk update
    - apk add openssh-client git zip curl
    - mkdir -p ~/.ssh
    - touch ~/.ssh/known_hosts
    - cat $Private_SSH_Key > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - ssh-keyscan -t rsa sftp.pedaweb.univ-amu.fr:8012 >> ~/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa
    - ssh-add -l
  script:
    - echo "ls -l " > sftp_commands
    - echo "cd public_html/extranet/" >> sftp_commands
    - echo "ls -l" >> sftp_commands
    - echo "put -r ./build/*" >> sftp_commands
    - cat sftp_commands | sftp -i ~/.ssh/id_rsa -oStrictHostKeyChecking=no -P 8012 sftp@sftp.pedaweb.univ-amu.fr  
