// 42 cells
// 6 rows 
// 7 columns
export const cells = [
    {
        "index": 0,
        "row": 0,
        "col": 0,
        "value": 0,
    },
    {
        "index": 1,
        "row": 0,
        "col": 1,
        "value": 0,
    },
    {
        "index": 2,
        "row": 0,
        "col": 2,
        "value": 0,
    },
    {
        "index": 3,
        "row": 0,
        "col": 3,
        "value": 0,
    },
    {
        "index": 4,
        "row": 0,
        "col": 4,
        "value": 0,
    },
    {
        "index": 5,
        "row": 0,
        "col": 5,
        "value": 0,
    },
    {
        "index": 6,
        "row": 0,
        "col": 6,
        "value": 0,
    },
    {
        "index": 7,
        "row": 1,
        "col": 0,
        "value": 0,
    },
    {
        "index": 8,
        "row": 1,
        "col": 1,
        "value": 0,
    },
    {
        "index": 9,
        "row": 1,
        "col": 2,
        "value": 0,
    },
    {
        "index": 10,
        "row": 1,
        "col": 3,
        "value": 0,
    },
    {
        "index": 11,
        "row": 1,
        "col": 4,
        "value": 0,
    },
    {
        "index": 12,
        "row": 1,
        "col": 5,
        "value": 0,
    },
    {
        "index": 13,
        "row": 1,
        "col": 6,
        "value": 0,
    },
    {
        "index": 14,
        "row": 2,
        "col": 0,
        "value": 0,
    },
    {
        "index": 15,
        "row": 2,
        "col": 1,
        "value": 0,
    },
    {
        "index": 16,
        "row": 2,
        "col": 2,
        "value": 0,
    },
    {
        "index": 17,
        "row": 2,
        "col": 3,
        "value": 0,
    },
    {
        "index": 18,
        "row": 2,
        "col": 4,
        "value": 0,
    },
    {
        "index": 19,
        "row": 2,
        "col": 5,
        "value": 0,
    },
    {
        "index": 20,
        "row": 2,
        "col": 6,
        "value": 0,
    },
    {
        "index": 21,
        "row": 3,
        "col": 0,
        "value": 0,
    },
    {
        "index": 22,
        "row": 3,
        "col": 1,
        "value": 0,
    },
    {
        "index": 23,
        "row": 3,
        "col": 2,
        "value": 0,
    },
    {
        "index": 24,
        "row": 3,
        "col": 3,
        "value": 0,
    },
    {
        "index": 25,
        "row": 3,
        "col": 4,
        "value": 0,
    },
    {
        "index": 26,
        "row": 3,
        "col": 5,
        "value": 0,
    },
    {
        "index": 27,
        "row": 3,
        "col": 6,
        "value": 0,
    },
    {
        "index": 28,
        "row": 4,
        "col": 0,
        "value": 0,
    },
    {
        "index": 29,
        "row": 4,
        "col": 1,
        "value": 0,
    },
    {
        "index": 30,
        "row": 4,
        "col": 2,
        "value": 0,
    },
    {
        "index": 31,
        "row": 4,
        "col": 3,
        "value": 0,
    },
    {
        "index": 32,
        "row": 4,
        "col": 4,
        "value": 0,
    },
    {
        "index": 33,
        "row": 4,
        "col": 5,
        "value": 0,
    },
    {
        "index": 34,
        "row": 4,
        "col": 6,
        "value": 0,
    },
    {
        "index": 35,
        "row": 5,
        "col": 0,
        "value": 0,
    },
    {
        "index": 36,
        "row": 5,
        "col": 1,
        "value": 0,
    },
    {
        "index": 37,
        "row": 5,
        "col": 2,
        "value": 0,
    },
    {
        "index": 38,
        "row": 5,
        "col": 3,
        "value": 0,
    },
    {
        "index": 39,
        "row": 5,
        "col": 4,
        "value": 0,
    },
    {
        "index": 40,
        "row": 5,
        "col": 5,
        "value": 0,
    },
    {
        "index": 41,
        "row": 5,
        "col": 6,
        "value": 0,
    }
];  